### ISSUE TITLE
Change church

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/B1Mobile#18]
When church is changed via church search page, practically a user can get into any church. Now what happens is we need a personId and some permissions related to donations for actual making a donation or perform some action. 

Think through what can be done here. 

cc @jzongker

**Comment by jzongker** [comment]
Closing this issue since we discussed over chat a while back.  It's ok for anyone to access any church (their permissions will be very limited). Appbase/loginpage with automatically create a Person record for the User when this happens or claim the existing one based on matching email.  B1Mobile will need similar behavior.
