### ISSUE TITLE
the icons have ? Marks instead of the designated icon.

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/B1Mobile#41]
![image3](https://user-images.githubusercontent.com/65249159/180891197-f6f50be9-d654-4291-bb06-eda92625a123.png)

**Comment by jzongker** [comment]
This was due to switching from FontAwesome to MaterialIcons.  I've pushed an update to correct this. If it isn't immediately resolved, force close and re-open the app and it should look correct.

![Screenshot_20220802-141103](https://user-images.githubusercontent.com/1447203/182454669-29c3a4d8-e934-446d-9203-0c039af46879.png)
